Bump up tiledb version to 2.21.1
TileDB-Inc/TileDB-Vector-Search pull request #291
Opened 2024-03-22 12:22 UTC by dudoslav

Bump up:

TileDB-Py version to 0.27.0
TileDB version to 2.21.1

NOTE: I had to modify `DownloadPrebuiltTileDB.cmake` since we are still using superbuild. Also source distribution needs its own logic added.

This should be release: `2.0`

2024-03-22 13:10 UTC, ihnorton approved these changes
(FWIW I thought we were going to pull the `DownloadPrebuildTiledb.cmake` from the release bundle, but up to you if you prefer to vendor it)

2024-03-27 02:37 UTC, ihnorton requested changes
Needs approval of the CI-fix commit I just added, before merging.

2024-03-27 02:37 UTC, ihnorton commented on src/include/test/unit_api_ivf_flat_index.cc
> +      CHECK(recall >= .999);
@lums658 @jparismorgan please confirm if this is ok. The rest of the higher-precision comparisons in this file are like this. We saw a failure here in [this run](https://github.com/TileDB-Inc/TileDB-Vector-Search/actions/runs/8438568931/job/23111048191?pr=291):
```
9: /home/runner/work/TileDB-Vector-Search/TileDB-Vector-Search/src/include/test/unit_api_ivf_flat_index.cc:285: FAILED:
9:   CHECK( recall == 1.0 )
9: with expansion:
9:   0.999 == 1.0
9: with message:
```

2024-03-27 11:07 UTC, jparismorgan approved these changes

2024-03-28 11:51 UTC, ihnorton approved these changes

2024-03-28 16:46 UTC, merged